### ISSUE TITLE
Cucumber vs Rspec Integration

### ISSUE THREAD

**Issue by amejiarosario** [rails3book/ticketee-v2#1]
Hi Ryan,
I'm reading your book (BTW, good work!) and following the examples to build ticketee v1. I notice that in the v2 there is no cucumber features. Are you planning to move away cucumber and use rspec integration test instead?Let me know your motives for that, your answer might help me in doing a better job testing in my rails projects. Thanks

**Comment by radar** [comment]
Yes, I'm planning to move away from Cucumber altogether because it's cumbersome and leads to people getting confused over what a Cucumber step is and what Capybara is. 

I've found that Cucumber can be useful if you're on a team of people where someone's vetting that the stories are doing what they should be, but it's _very_ rare that someone is actually going to be in that role.

That's why I like Capybara. It's Ruby and therefore understandable, there's no extra `Given`/`When`/`Then` crap necessary to understand and the scenarios are _still_ as readable as their Cucumber counterparts. 

You should be using Capybara if the majority of people on your team are people who write the code and need to understand how things work.

**Comment by amejiarosario** [comment]
Sounds pretty reasonable. Now, I'm trying to follow your book's Cucumber features using RSpec with Capybara. However, it's taking me much more time... Do you have an estimate when your 2nd edition book is coming out?

**Comment by radar** [comment]
The first five chapters were supposed to be released at the end of last week or beginning of this week, and that's not happened obviously... So I'd hope pretty soon.

The next five after that will be posted shortly there after, then each chapter we do I'm going to try to get them to MEAP that.

**Comment by radar** [comment]
What issues are you running into?

**Comment by amejiarosario** [comment]
Well, I'm right now reading and doing the chapter 7 (Basic Access Control). I had some issues with the authentication with RSpec using FactoryGirl and Devise, but I just found a nice examples in your ticketee-v2 repo. So, I'm getting the theory from the book and trying to match it with the v2 examples... 
(BTW, If you need someone to review the early drafts or follow along the code examples let me know, as a newbie I might be able to provide some comments)

**Comment by radar** [comment]
Sure, that'd be really helpful. I've sent you an email regarding that.
